In [1]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "The customer was charged twice for the same transaction."

tokens = tokenizer.tokenize(text)


tokens

/Users/van/Documents/Van/Code/laya-from-scratch/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


['the',
 'customer',
 'was',
 'charged',
 'twice',
 'for',
 'the',
 'same',
 'transaction',
 '.']

In [2]:
text = "The customer requested tokenization."

tokenizer.tokenize(text)

['the', 'customer', 'requested', 'token', '##ization', '.']

In [3]:
encoded = tokenizer(
    text,
    return_tensors="pt",
)

encoded

{'input_ids': tensor([[  101,  1996,  8013,  7303, 19204,  3989,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [4]:
encoded["input_ids"]

tensor([[  101,  1996,  8013,  7303, 19204,  3989,  1012,   102]])

In [5]:
tokenizer.convert_ids_to_tokens(encoded["input_ids"][0])

['[CLS]', 'the', 'customer', 'requested', 'token', '##ization', '.', '[SEP]']

In [6]:
backbone = AutoModel.from_pretrained("bert-base-uncased")
outputs = backbone(**encoded)
outputs, outputs.last_hidden_state.shape

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 14446.35it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


(BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.3585, -0.0562, -0.3552,  ..., -0.3049, -0.0626,  0.7158],
          [-0.3415, -0.2205, -0.2199,  ...,  0.2218,  0.4299,  0.6785],
          [ 0.0328, -0.9895,  0.1472,  ..., -0.0025, -0.0720,  0.8429],
          ...,
          [-0.0905, -0.7260, -0.4433,  ..., -0.1704, -0.1435,  0.9385],
          [-0.4427, -0.9306, -0.2404,  ...,  0.2166,  0.4173, -0.1078],
          [ 0.7043,  0.2043, -0.4916,  ...,  0.1960, -0.6928, -0.0702]]],
        grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.8781, -0.3721, -0.7515,  0.6661,  0.4495, -0.2297,  0.8770,  0.2556,
          -0.5768, -1.0000, -0.2504,  0.5918,  0.9736,  0.2974,  0.8386, -0.6942,
          -0.3537, -0.4728,  0.3551, -0.3476,  0.4118,  0.9999,  0.2426,  0.2951,
           0.4436,  0.7601, -0.5191,  0.8627,  0.9488,  0.7149, -0.5570,  0.1742,
          -0.9774, -0.2652, -0.8304, -0.9881,  0.2774, -0.7398, -0.0901,  0.0119,
          -0.8734,  

In [12]:
text = """
The customer was charged twice for the same transaction.
Which department should handle this?
[MASK] Billing
[MASK] Technical support
[MASK] Sales
"""

encoded = tokenizer(
    text,
    return_tensors="pt",
)
tokens = tokenizer.convert_ids_to_tokens(encoded["input_ids"][0])

tokens

['[CLS]',
 'the',
 'customer',
 'was',
 'charged',
 'twice',
 'for',
 'the',
 'same',
 'transaction',
 '.',
 'which',
 'department',
 'should',
 'handle',
 'this',
 '?',
 '[MASK]',
 'billing',
 '[MASK]',
 'technical',
 'support',
 '[MASK]',
 'sales',
 '[SEP]']

In [ ]:
tokenizer.tokenize(text), tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text))

(['the',
  'customer',
  'was',
  'charged',
  'twice',
  'for',
  'the',
  'same',
  'transaction',
  '.',
  'which',
  'department',
  'should',
  'handle',
  'this',
  '?',
  '[MASK]',
  'billing',
  '[MASK]',
  'technical',
  'support',
  '[MASK]',
  'sales'],
 [1996,
  8013,
  2001,
  5338,
  3807,
  2005,
  1996,
  2168,
  12598,
  1012,
  2029,
  2533,
  2323,
  5047,
  2023,
  1029,
  103,
  25640,
  103,
  4087,
  2490,
  103,
  4341])

In [8]:
option_mask = encoded["input_ids"] == tokenizer.mask_token_id
option_mask.sum()

tensor(3)

In [7]:
from laya.pretrained import PretrainedDecisionModel

model = PretrainedDecisionModel(
    model_name="bert-base-uncased",
    decision_hidden_dim=128,
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 26206.99it/s]
[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [8]:
text = """
The customer was charged twice for the same transaction.
Which department should handle this?
[MASK] Billing
[MASK] Technical support
[MASK] Sales
"""

encoded = tokenizer(
    text,
    return_tensors="pt",
)

option_mask = encoded["input_ids"] == tokenizer.mask_token_id

In [9]:
logits, probabilities = model(
    input_ids=encoded["input_ids"],
    attention_mask=encoded["attention_mask"],
    option_mask=option_mask,
)
logits, probabilities

(tensor([[-0.0101, -0.0693, -0.1002]], grad_fn=<SqueezeBackward1>),
 tensor([[0.3501, 0.3300, 0.3199]], grad_fn=<SoftmaxBackward0>))

In [11]:
probabilities.sum(dim=-1)

tensor([1.], grad_fn=<SumBackward1>)

In [16]:
model.backbone.get_input_embeddings()

Embedding(30522, 768, padding_idx=0)

In [18]:
vocab = tokenizer.get_vocab()
len(vocab)

30522

In [19]:
for word in [
    "customer",
    "customers",
    "tokenization",
    "cryptocurrency",
    "microstructure",
]:
    print(
        word,
        "→",
        tokenizer.tokenize(word),
    )

customer → ['customer']
customers → ['customers']
tokenization → ['token', '##ization']
cryptocurrency → ['crypt', '##oc', '##ur', '##ren', '##cy']
microstructure → ['micro', '##st', '##ru', '##cture']


In [21]:
tokenizer.cls_token, tokenizer.sep_token, tokenizer.mask_token, tokenizer.pad_token, tokenizer.unk_token

('[CLS]', '[SEP]', '[MASK]', '[PAD]', '[UNK]')

In [22]:
texts = [
    """
    The customer was charged twice.
    Which department should handle this?
    [MASK] Billing
    [MASK] Technical support
    [MASK] Sales
    """,
    """
    The application crashes after login.
    Which department should handle this?
    [MASK] Billing
    [MASK] Technical support
    [MASK] Sales
    """,
]

encoded = tokenizer(texts, padding=True, truncation=True, return_tensors="pt")
print(encoded["input_ids"].shape)
print(encoded["attention_mask"].shape)

torch.Size([2, 22])
torch.Size([2, 22])


In [25]:
option_mask = encoded["input_ids"] == tokenizer.mask_token_id
option_mask, option_mask.sum(dim=1)

(tensor([[False, False, False, False, False, False, False, False, False, False,
          False, False, False,  True, False,  True, False, False,  True, False,
          False, False],
         [False, False, False, False, False, False, False, False, False, False,
          False, False, False, False,  True, False,  True, False, False,  True,
          False, False]]),
 tensor([3, 3]))

In [ ]:
logits, proba = model(
    input_ids=encoded["input_ids"],
    attention_mask=encoded["attention_mask"],
    option_mask=option_mask,
)
logits, proba

(tensor([[-0.0143, -0.0762, -0.1017],
         [ 0.0041, -0.0334, -0.0753]], grad_fn=<SqueezeBackward1>),
 tensor([[0.3501, 0.3291, 0.3208],
         [0.3464, 0.3337, 0.3200]], grad_fn=<SoftmaxBackward0>))